### ISSUE TITLE
not authorized

### ISSUE THREAD

**Issue by superggfun** [openraildata/stomp-client-go#1]
XXX is not authorized to read from: topic://

**Comment by poggs** [comment]
It sounds like you're trying to access a topic that the remote server hasn't allowed you to access.  Can you be more specific on what the problem is, which topic it is?

**Comment by superggfun** [comment]
I have registered an account with NetworkRail (https://datafeeds.networkrail.co.u) and the User state is Active. Feeds choose Train Movements General. Then also is not authorized. I also notice that the website have a "Security Token" Do I need to input it.

2023/02/17 18:50:00 Connecting: datafeeds.networkrail.co.uk:61618 ...
2023/02/17 18:50:00 Connected: ID:opendata-prod.rockshore.net-36403-1676373830921-2:260267
2023/02/17 18:50:00 Subscribed:  (1)
2023/02/17 18:50:01 ERROR: received ERROR; Closing underlying connection
2023/02/17 18:50:01 INFO: Subscription 1: /topic/Train Movements General: ERROR message:User XXX@XXX.ac.uk is not authorized to read from: topic://Train Movements General
2023/02/17 18:50:06 Cleaning-up...
2023/02/17 18:50:06 Unsubscribing from subscription ...
2023/02/17 18:50:06 Successfully unsubscribed from subscription .
2023/02/17 18:50:06 Disconnecting from connection...
2023/02/17 18:50:06 Sucessfully disconnected from connection.

**Comment by seawolf** [comment]
I have answered in your other thread, https://github.com/openraildata/stomp-client-go/issues/2
