### ISSUE TITLE
`Unauthorized` error when using `Train Movements General` feed

### ISSUE THREAD

**Issue by superggfun** [openraildata/stomp-client-go#2]
I have registered an account with NetworkRail (https://datafeeds.networkrail.co.uk) and the User state is `Active`.
From the Feeds, I choose `Train Movements General`. However, when I connect with this software, it is `not authorized` (see below).

I also notice that the website has a "Security Token"  -  do I need to input it?

```
2023/02/17 18:50:00 Connecting: datafeeds.networkrail.co.uk:61618 ...
2023/02/17 18:50:00 Connected: ID:opendata-prod.rockshore.net-36403-1676373830921-2:260267
2023/02/17 18:50:00 Subscribed:  (1)
2023/02/17 18:50:01 ERROR: received ERROR; Closing underlying connection
2023/02/17 18:50:01 INFO: Subscription 1: /topic/Train Movements General: ERROR message:User XXX@XXX.ac.uk is not authorized to read from: topic://Train Movements General
2023/02/17 18:50:06 Cleaning-up...
2023/02/17 18:50:06 Unsubscribing from subscription ...
2023/02/17 18:50:06 Successfully unsubscribed from subscription .
2023/02/17 18:50:06 Disconnecting from connection...
2023/02/17 18:50:06 Sucessfully disconnected from connection.
```

_Originally posted by @superggfun in https://github.com/openraildata/stomp-client-go/issues/1#issuecomment-1435110853_

**Comment by seawolf** [comment]
The error you're receiving is that the topic ID is incorrect:  `topic://Train Movements General`

The feeds must be referenced by their codes, as told in the README:
```
FEEDS_TRAIN_MOVEMENTS=TRAIN_MVT_HY_TOC,TRAIN_MVT_ET_TOC
```

For your particular case, it will be:  `FEEDS_TRAIN_MOVEMENTS=TRAIN_MVT_GENERAL`

The full list at present (viewable by the HTML source code for the page) is:
 * `TRAIN_MVT_ALL_TOC` - All TOCs
 * `TRAIN_MVT_GENERAL` - Train Movements: General
 * `TRAIN_MVT_FREIGHT` - Train Movements: Freight
 * `TRAIN_MVT_HL_TOC` - Arriva Trains Wales
 * `TRAIN_MVT_ES_TOC` - Caledonian Sleeper
 * `TRAIN_MVT_HT_TOC` - c2c
 * `TRAIN_MVT_EH_TOC` - CrossCountry
 * `TRAIN_MVT_EN_TOC` - Devon & Cornwall Railways
 * `TRAIN_MVT_EM_TOC` - East Midlands Trains
 * `TRAIN_MVT_GA_TOC` - Eurostar (UK) Ltd
 * `TRAIN_MVT_XJ_TOC` - Ffestiniog Railway
 * `TRAIN_MVT_EG_TOC` - First Capital Connect
 * `TRAIN_MVT_EF_TOC` - First Great Western
 * `TRAIN_MVT_PF_TOC` - First Hull Trains
 * `TRAIN_MVT_HA_TOC` - First Scotrail
 * `TRAIN_MVT_EA_TOC` - First Transpennine Express
 * `TRAIN_MVT_HV_TOC` - Gatwick Express Ltd
 * `TRAIN_MVT_EC_TOC` - Grand Central
 * `TRAIN_MVT_EE_TOC` - Heathrow Connect
 * `TRAIN_MVT_HM_TOC` - Heathrow Express Ltd
 * `TRAIN_MVT_HZ_TOC` - Island Lines
 * `TRAIN_MVT_EJ_TOC` - London Midland
 * `TRAIN_MVT_EK_TOC` - London Overground
 * `TRAIN_MVT_XC_TOC` - LUL Bakerloo Line
 * `TRAIN_MVT_XE_TOC` - LUL District Line – Richmond
 * `TRAIN_MVT_XB_TOC` - LUL District Line – Wimbledon
 * `TRAIN_MVT_HE_TOC` - Merseyrail
 * `TRAIN_MVT_EB_TOC` - National Express East Anglia
 * `TRAIN_MVT_HB_TOC` - National Express East Coast
 * `TRAIN_MVT_PG_TOC` - Nexus
 * `TRAIN_MVT_PR_TOC` - North Yorkshire Moors Railway
 * `TRAIN_MVT_ED_TOC` - Northern Rail
 * `TRAIN_MVT_HU_TOC` - Southeastern
 * `TRAIN_MVT_HW_TOC` - Southern
 * `TRAIN_MVT_HY_TOC` - South Western Railway (Stagecoach)
 * `TRAIN_MVT_EX_TOC` - TfL Rail
 * `TRAIN_MVT_HO_TOC` - Chiltern
 * `TRAIN_MVT_HF_TOC` - Virgin West Coast
 * `TRAIN_MVT_PA_TOC` - West Coast Railway Co.
 * `TRAIN_MVT_EI_TOC` - Wrexham & Shropshire Railway

**Comment by seawolf** [comment]
The `Security Token` is not needed, as this software connects using the same username/password as you do to the website.

**Comment by superggfun** [comment]
![image](https://user-images.githubusercontent.com/89253691/222006123-cdc3eccf-c38c-480c-96e3-666e8dede016.png)
Still not authorized

**Comment by seawolf** [comment]
What happens when you set `FEEDS_TRAIN_MOVEMENTS` to one of [the correct values](https://github.com/openraildata/stomp-client-go/issues/2#issuecomment-1436561160), corresponding to what you have selected in the NR Data Feeds website?

The screenshot shows `TRAIN_MVT_01_TOC` etc. being used, which are incorrect.

**Comment by superggfun** [comment]
![image](https://user-images.githubusercontent.com/89253691/222154608-600393a6-170e-49cd-be0c-4532b5a49d7d.png)

**Comment by seawolf** [comment]
```go
os.SetEnv("FEEDS_TRAIN_MOVEMENTS", "TRAIN_MVT_GENERAL")
```

**Comment by superggfun** [comment]
![image](https://user-images.githubusercontent.com/89253691/222160049-652d9f6a-2d0f-46e7-9b64-5db78f2d7016.png)

**Comment by seawolf** [comment]
Thanks! This now confirms your username & password are correct, and are trying to connect to a valid feed.

There are a couple of ways to progress:

1. Please may you provide a screenshot of the "My Feeds" page, showing which feeds you are authorised/subscribed to?
  https://datafeeds.networkrail.co.uk/ntrod/myFeeds
  ![https://datafeeds.networkrail.co.uk/ntrod/myFeeds](https://user-images.githubusercontent.com/193455/222166758-7064d36f-c2b3-4de7-8d85-0c39fdf3060d.png)
  
2. If you are subscribed to multiple feeds, please can you unsubscribe from all _other_ feeds and try again?
  (There is sometimes conflict between certain combinations, so working with one feed at a time can avoid confusion.)

**Comment by superggfun** [comment]
![image](https://user-images.githubusercontent.com/89253691/222196794-19646932-3ff7-4b5d-9bfb-5d20caaa3d9e.png)

**Comment by superggfun** [comment]
Still not authorized

**Comment by seawolf** [comment]
Thanks for your continued efforts, @superggfun!

Interestingly, I am able to replicate the same behaviour! My account is able to TOC-specific feeds and the "all TOCs" one, but **not** `TRAIN_MVT_GENERAL` nor TRAIN_MVT_FREIGHT`, despite the NR website letting me subscribe.

The software shouldn't differentiate and the error message is coming from Network Rail's systems, so I think you need to talk with Network Rail support about it:  https://wiki.openraildata.com//index.php?title=About_the_Network_Rail_feeds#Support

@poggs  --  is there anything different about the two "general" feeds that would refuse us access?
_(If so, it might be worth noting on [the wiki page](https://wiki.openraildata.com/index.php?title=Train_Movements#Message_Topics).)_

**Comment by superggfun** [comment]
Thank you for your reply.

**Comment by superggfun** [comment]
When I try to use TOC, also have problems.
![image](https://user-images.githubusercontent.com/89253691/222213648-72ed24fd-ee27-4b00-b8a7-7ca3d18cdcdf.png)
![image](https://user-images.githubusercontent.com/89253691/222213729-a01b0945-4041-4353-816d-bea4ce15859e.png)

**Comment by poggs** [comment]
You should really be using https://publicdatafeeds.networkrail.co.uk/ rather than the old platform, which doesn't have any per-operator message channels.

If you're still having problems, sign up to https://groups.google.com/g/openraildata-talk and post a message - it's much easier for people to help there as opposed to on a GitHub issue.
